function cnn_scotopic_mnist_demo(expID)
% cnn_scotopic_mnist_demo(expID)
% Demo how to train scotopic classifiers on MNIST
% (c) 2016 Bo Chen
% bchen3@caltech.edu

numEpochs = 80; 
thArray = log(logspace(log10(0.1+1e-4),log10(1-1e-4),200));
thArray = thArray([1:5:195 196:end]);
config = getScotopicConfig;
if config.use_gpu
    gpu = mod(expID,2)+1;
else
    gpu = [];
end

switch expID
    case 1
        % WaldNet
        lr = 0.004;
        [net, info, testinfo] = cnn_scotopic('dataset','mnist',...
            'modelType','waldnet-wb1',...
            'modelName',sprintf('val_lrx%ga0.00f',lr),...
            'sp', struct('mode','batch','alpha',0,'estimate_PPP',false), ...
            'thArray', thArray, ...
            'validate', true, ...
            'whitenData',false,...
            'contrastNormalization',false, ...
            'train', struct('gpus',gpu,...
            'learningRate',lr*ones(1,numEpochs),...
            'numEpochs',numEpochs));
    case 2
        % Rate
        lr = 0.001;
        [net, info, testinfo] = cnn_scotopic('dataset','mnist',...
            'modelType','lenet',...
            'modelName','val_rate',...
            'sp', struct('mode','batch','alpha',0), ...
            'thArray', thArray, ...
            'validate', true, ...
            'whitenData',false,...
            'contrastNormalization',false, ...
            'train', struct('gpus',gpu,...
            'learningRate',lr*ones(1,numEpochs),...
            'numEpochs',numEpochs));
    case {3,4,5,6}
        % Photoic
        PPPArray = [220 22 2.2 .22];
        PPP = PPPArray(expID-2);
        lr = 0.001;
        [net, info, testinfo] = cnn_scotopic('dataset','mnist',...
            'modelType','lenet',...
            'modelName',sprintf('val_p%g',PPP),...
            'sp', struct('mode','batch','PPPArray',PPP,'alpha',0), ...
            'thArray', thArray, ...
            'validate', true, ...
            'whitenData',false,...
            'contrastNormalization',false, ...
            'train', struct('gpus',gpu,...
            'learningRate',lr*ones(1,numEpochs),...
            'numEpochs',numEpochs));
    case 7
        % Ensemble
        lr = 0.001;
        PPPArray = [220 22 2.2 .22];
        [net, info, testinfo] = cnn_scotopic('dataset','mnist',...
            'modelType','ensemble',...
            'modelName','val_p',...
            'sp', struct('PPPArray',PPPArray,'alpha',0), ...
            'train', struct('learningRate',lr*ones(1,numEpochs),...
                            'numEpochs',numEpochs),...
            'thArray', thArray, ...
            'validate', true, ...
            'whitenData',false,...
            'contrastNormalization',false);
    case 8
        % WaldNet with lightlevel estimation
        lr = 0.004;
        [net, info, testinfo] = cnn_scotopic('dataset','mnist',...
            'modelType','waldnet-wb1',...
            'modelName',sprintf('val_lrx%ga0.00f',lr),...
            'sp', struct('mode','batch','alpha',0,'estimate_PPP',true), ...
            'thArray', thArray, ...
            'validate', true, ...
            'whitenData',false,...
            'contrastNormalization',false, ...
            'train', struct('gpus',gpu,...
            'learningRate',lr*ones(1,numEpochs),...
            'numEpochs',numEpochs));
        
end
