function cnn_scotopic_cifar_demo(expID)
% Demo how to train scotopic classifiers on CIFAR
% (c) 2016 Bo Chen
% bchen3@caltech.edu

numEpochs = 75;
config = getScotopicConfig;
if config.use_gpu
    gpu = mod(expID,2)+1;
else
    gpu = [];
end

switch expID
    case 1
        % WaldNet
        [net, info, testinfo] = cnn_scotopic('dataset','cifar',...
            'modelType','waldnet-wb1',...
            'modelName',sprintf('a1.00f'),...
            'sp', struct('mode','batch','alpha',1,'estimate_PPP',true), ...
            'validate', false, ...
            'whitenData',true,...
            'contrastNormalization',true, ...
            'train', struct('gpus',gpu));
    case 2
        % Rate
        [net, info, testinfo] = cnn_scotopic('dataset','cifar',...
            'modelType','lenet',...
            'modelName','rate',...
            'sp', struct('mode','batch','alpha',0), ...
            'validate', false, ...
            'whitenData',true,...
            'contrastNormalization',true, ...
            'train', struct('gpus',gpu));
    case {3,4,5,6}
        % Photoic
        PPPArray = [220 22 2.2 .22];
        PPP = PPPArray(expID-2);
        [net, info, testinfo] = cnn_scotopic('dataset','cifar',...
            'modelType','lenet',...
            'modelName',sprintf('p%g',PPP),...
            'sp', struct('mode','batch','PPPArray',PPP,'alpha',0), ...
            'validate', false, ...
            'whitenData',true,...
            'contrastNormalization',true, ...
            'train', struct('gpus',gpu));
    case 7
        % Ensemble
        PPPArray = [220 22 2.2 .22];
        [net, info, testinfo] = cnn_scotopic('dataset','cifar',...
            'modelType','ensemble',...
            'modelName','p',...
            'sp', struct('PPPArray',PPPArray,'alpha',0), ...
            'train', struct('gpus',gpu),...
            'validate', false, ...
            'whitenData',true,...
            'contrastNormalization',true);
        
end